<section class="home-page-content">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				<div class="mobile-app text-center">
					<img alt="" src="<?php echo $this->getSkinUrl().'images/homepage-image.png' ?>" class="img-responsive"/>
				</div>
			</div>
			<div class="col-lg-offset-1 col-md-offset-1 col-lg-4 col-md-4 col-sm-6 col-xs-12">
				<div class="mobile-app-content">
					<h4>Download the App</h4>
					<p>Download our free app from play store and app store to Order Food from Your Favorite Restaurants directly from your phone.</p>
				</div>
				<div class="download-app row">
					<div class="app_store col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<a href="https://itunes.apple.com/us/app/lunch-or-dinner/id1288531576?mt=8">
							<img alt="app_store" src="<?php echo $this->getSkinUrl().'images/ced_app_store.png' ?>" /></a>
					</div>
					<div class="play_store col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<a href="https://play.google.com/store/apps/details?id=com.lunch.dinner&hl=en">
							<img alt="play_store" src="<?php echo $this->getSkinUrl().'images/ced_play_store.png' ?>" />
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
